#
# Copyright (c) 2023-present VPMedia
# author: Andras Csizmadia <andras@vpmedia.hu>
# see https://docs.docker.com/compose/compose-file
#
services:
  dev_redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    volumes:
      - dev_redisinsight_data:/data

