#
# Copyright (c) 2023-present VPMedia
# author: Andras Csizmadia <andras@vpmedia.hu>
# see https://docs.docker.com/compose/compose-file
#
services:
  dev_otel:
    image: otel/opentelemetry-collector-contrib:0.87.0
    restart: unless-stopped
    env_file:
      - dev_otel.env
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./dockerfiles/otel/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133" # Health check
      - "1777:1777"   # Performance profile
      - "55679:55679" # Service debugger
    depends_on:
      - dev_jaeger
