#
# Copyright (c) 2023-present VPMedia
# author: Andras Csizmadia <andras@vpmedia.hu>
# see https://docs.docker.com/compose/compose-file
#
services:
 dev_prometheus:
    image: prom/prometheus:v2.50.1
    restart: unless-stopped
    env_file:
      - dev_prometheus.env
    ports:
      - "9090:9090" # Serve frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dockerfiles/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - dev_prometheus_data:/prometheus
    depends_on:
      - dev_otel
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1d"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
 