receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "http://127.0.0.1"
            - "http://localhost"

exporters:
  logging:
  otlp:
    endpoint: "dev_jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1777"
    block_profile_fraction: 0
    mutex_profile_fraction: 0
  zpages:
    endpoint: "0.0.0.0:55679"

connectors:
  spanmetrics:
    namespace: span.metrics

service:
  telemetry:
    logs:
      level: "info"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [logging, prometheus]
