global:
  scrape_interval: 1m

scrape_configs:

  - job_name: "dev_grafana"
    static_configs:
      - targets: ["dev_grafana:3000"]

  - job_name: "dev_otel_collector"
    static_configs:
      - targets: ["dev_otel:8888"]

  - job_name: "dev_otel_exporter"
    static_configs:
      - targets: ["dev_otel:8889"]

